<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

use UserBundle\Entity\User;
use AppBundle\Entity\Issue;
use AppBundle\Entity\Project;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function findByUser(User $user)
    {
        $query = $this->createQueryBuilder('activity');

        $query
            ->leftJoin('activity.project', 'p')
            ->leftJoin('activity.issue', 'i')
            ->leftJoin('activity.user', 'u')
            ->where('u.id = :user_id')
            ->setParameter('user_id', $user->getId())
            ->orderBy('activity.created', 'DESC')
            ->setMaxResults(16);

        return $query->getQuery()->getResult();
    }

    public function findByIssue(Issue $issue)
    {
        $query = $this->createQueryBuilder('activity');

        $query
            ->leftJoin('activity.project', 'p')
            ->leftJoin('activity.issue', 'i')
            ->leftJoin('activity.user', 'u')
            ->where('i.id = :issue_id')
            ->setParameter('issue_id', $issue->getId())
            ->orderBy('activity.created', 'DESC')
            ->setMaxResults(16);

        return $query->getQuery()->getResult();
    }

    public function findByProject(Project $project)
    {
        $query = $this->createQueryBuilder('activity');

        $query
            ->leftJoin('activity.project', 'p')
            ->leftJoin('activity.issue', 'i')
            ->leftJoin('activity.user', 'u')
            ->where('p.id = :project_id')
            ->setParameter('project_id', $project->getId())
            ->orderBy('activity.created', 'DESC')
            ->setMaxResults(16);

        return $query->getQuery()->getResult();
    }
}