<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

use UserBundle\Entity\User;
use AppBundle\Entity\Mapping\EnumStatusIssue;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends EntityRepository
{
    public function findByUser(User $user)
    {
        $query = $this->createQueryBuilder('issue');

        $query->where('issue.assignee = :user_id')
            ->andwhere('issue.status = :status')
            ->setParameters([
                'user_id' => $user->getId(),
                'status' => EnumStatusIssue::OPEN
            ]);

        return $query->getQuery()->getResult();
    }

    public function findByCollaborator(User $user)
    {
        $query = $this->createQueryBuilder('issue');

        $query->leftJoin('issue.collaborators', 'c')
            ->where('c.id = :user_id')
            ->andwhere('issue.status = :status')
            ->setParameters([
                'user_id' => $user->getId(),
                'status' => EnumStatusIssue::OPEN
            ]);

        return $query->getQuery()->getResult();
    }
}