<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

use UserBundle\Entity\User;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function findByUsers(User $user, $form = false)
    {
        $query = $this->createQueryBuilder('project');

        $query->leftJoin('project.users', 'users')
                ->where('users.id = :user_id')
                ->setParameter('user_id', $user->getId());

        if ($form)
            return $query;

        return $query->getQuery()->getResult();
    }
}