services:
    project.security.voter:
        class:      AppBundle\Security\ProjectVoter
        public:     false
        arguments:
            - @security.role_hierarchy
        tags:
            - { name: security.voter }

    issue.security.voter:
        class:      AppBundle\Security\IssueVoter
        public:     false
        arguments:
            - @security.role_hierarchy
        tags:
            - { name: security.voter }

    comment.security.voter:
        class:      AppBundle\Security\CommentVoter
        public:     false
        arguments:
            - @security.role_hierarchy
        tags:
            - { name: security.voter }

    project.form.type:
        class: AppBundle\Form\ProjectFormType
        tags:
            - { name: form.type, alias: app_project }

    issue.form.type:
        class: AppBundle\Form\IssueFormType
        arguments:
            - @security.token_storage
        tags:
            - { name: form.type, alias: app_issue }

    comment.form.type:
        class: AppBundle\Form\CommentFormType
        tags:
            - { name: form.type, alias: app_issue_comment }

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments:
            - @security.token_storage
        tags:
            - { name: twig.extension }

    collaborator.listener:
        class: AppBundle\EventListener\CollaboratorEventListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }

    activity.listener:
        class: AppBundle\EventListener\ActivityEventListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }